### ISSUE TITLE
要怎么样才能支持私聊啊？

### ISSUE THREAD

**Issue by XiaoFuOS** [Ice9Coffee/HoshinoBot#275]
想弄个支持私聊和群聊的功能

**Comment by Ice9Coffee** [comment]
HoshinoBot的架构主要为群聊设计，Service组需要依靠group_id来区分启用状态，不支持私聊功能。

你可以使用nonebot原始的装饰器`on_command`来实现私聊功能。

如果希望Service的装饰器也在私聊触发，你需要修改hoshino/msghandler.py与hoshino/service.py（不推荐，可能会影响所有插件）
