### ISSUE TITLE
安装requirements.txt 时 No matching distribution found for Quart==0.14.1 (from -r requirements.txt (line 1))

### ISSUE THREAD

**Issue by q1575825411** [Ice9Coffee/HoshinoBot#285]
ERROR: Could not find a version that satisfies the requirement Quart==0.14.1 (from -r requirements.txt (line 1)) (from versions: none)
ERROR: No matching distribution found for Quart==0.14.1 (from -r requirements.txt (line 1)) 

疑似版本问题，现在用的是什么版本呢

**Comment by Ice9Coffee** [comment]
检查一下python与pip版本

**Comment by q1575825411** [comment]
已调整，谢谢大佬
