### ISSUE TITLE
如何只允许让超级管理员启用某个插件

### ISSUE THREAD

**Issue by xixi-furry** [Ice9Coffee/HoshinoBot#286]
插件里用了 manage_priv=priv.SUPERUSER。但是群主还是可以启用

**Comment by Ice9Coffee** [comment]
检查一下配置文件，配置文件的优先级大于代码指定。
配置文件路径：`~/.hoshino/service_config/{ServiceName}.json`

**Comment by xixi-furry** [comment]
感谢大佬的指导，已经发现有这个问题了，请问一下具体的superuser的权限值是多少？或者我直接把这个config删了重新让其启用生成一个是不是也可以x

**Comment by Ice9Coffee** [comment]
是999，你可以在priv.py中找到定义。
你也可以指定任意数值的权限。

删除配置文件会导致启用/禁用的群失效（会恢复为代码指定的默认值）

**Comment by xixi-furry** [comment]
刚刚看到定义了，谢谢大佬！
